### ISSUE TITLE
Example with squares

### ISSUE THREAD

**Issue by cmacdonnacha** [sarmad1995/react-native-easy-content-loader#6]
Hi, nice work on this so far, looks great!

I can't see any customized examples with squares. Can you tell me how I could achieve something like this:

![image](https://user-images.githubusercontent.com/9777763/66271008-2d35b400-e851-11e9-9e8d-b21e115570c2.png)

**Comment by sarmad1995** [comment]
For squares there is only support for `pWidth` and `pHeight`, But i am planning to add pHeight in array as well, same like `pWidth` so can we can add many paragraphs with different dimensions.

**Comment by cmacdonnacha** [comment]
Thanks. Do you have an example of a single square? This doesn't seem to work:

`<ContentLoader active aShape={'square'}/>`

**Comment by sarmad1995** [comment]
@cmacdonnacha  Just pushed the new update with `pHeight` as array, 
It might help you.
Do remember, the package is changed to `@sarmad1995/react-native-content-loader`

**Comment by cmacdonnacha** [comment]
Ended up writing my own @sarmad1995 thanks anyway
